'use client'
import {useImageFox} from '../hook/useImageFox';
import LazyImage from '../components/LazyImage';
import Head from 'next/head';


function Home():JSX.Element {
  const {addNewImage,images}=useImageFox()

 
  return (
  <>
    <Head>
    <title> Imágenes de Zorros</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <script
          defer
          data-domain="yourdomain.com"
          src="https://plausible.io/js/script.js"
        ></script>
  </Head>
    <div className='text-center : space-y-5 w-full h-full m-5 '>
    <h3 className=': uppercase font-bold text-lila'>Curso React con Typescript</h3>
    <h1 className="uppercase text-center text-3xl font-bold ">Componente Lazy Image</h1>
    <p className='text-lg text-gray-500 font-thin'>Un componente genérico de React para cargar imágenes con Lazy Loading</p>
    <p className='text-lg text-gray-500 font-thin'>Las imágenes agregadas no se descargarán hasta que no sean visibles en la pantalla</p>
    <button className=" bg-lila px-5 py-2 text-white  rounded  uppercase font-bold hover:bg-purple-800" onClick={addNewImage}>Add New Image</button>
   <div className=' w-full  grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2  place-content-center '>
   { 
      images.map(({id,image},index)=>(
        <div key={id} className='w-full flex items-center '>
         <LazyImage 
              src={image}
              alt={`Imagen de zorro ${index+1}` }
              width="320"
              height="auto"
              className="mx-auto rounded-md bg-gray-300"
              onClick={() => {
                alert(`Esta es la imagen ${index+1}`);
              }} 
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }}
              />
        </div>
      ))
    } 
   </div>
    </div>
    </>
    
    )

}
export default Home